### ISSUE TITLE
Problem while decoding DAT files in wrd_data folder

### ISSUE THREAD

**Issue by AOLebets** [redssu/Harmony-Tools#10]
No matter which .DAT file from the wrd_data folder of the game I want to extract I see this stacktrace
![image](https://github.com/redssu/Harmony-Tools/assets/89778658/072b3500-4468-421c-8975-e4d9b11d0550)
It happens with every .DAT associated with nonstop, hanron, kokoronpa, nico or panic folders. When I go to minigame folder and try working with those (anagram for example) I get the clear .dat.csv's.
I'm using the 2.0.6 release (even though file inpection says it's version 2.0.5.0). What should I do? Is it supposed to be like that?

**Comment by P4K5** [comment]
Hi,
you can't extract .dat files from wrd_data folder with this tool. This tool was made to be able to extract .dat files from the minigame folder, not from wrd_data.

Therefore, it cannot extract files from wrd_data with a tool created for minigame files.

If you want to extract files from wrd_data you should look for another tool.

**Comment by redssu** [comment]
Yeah, as @P4K5 already said, the DAT tool is designed to work with minigame files, the DAT files in `wrd_data` are different ones with completely different format.
