### ISSUE TITLE
Legace tools

### ISSUE THREAD

**Issue by ilyaszeke** [redssu/Harmony-Tools#12]
I don't know, but where is the legacy version of the tools? The documentation is just based on it.

**Comment by redssu** [comment]
If you want to use legacy version of tools - it can be found in "[Releases](https://github.com/redssu/Harmony-Tools/releases)" section - all of the "1.x.x" versions are the legacy ones. [Here's a link to last legacy release (1.0.8).](https://github.com/redssu/Harmony-Tools/releases/tag/v1.0.8)

As far as I remember, I updated the docs alongside with new tools release (2.x.x), however I noticed that I missed the one about "[How to extract game's scripts?](https://github.com/redssu/Harmony-Tools/wiki/How-to-extract-the-game's-scripts%3F)". The rest of documentation should work for both 1.x.x and 2.x.x releases, as the Context Menu didn't change a lot. 

Feel free to ask any other questions - you can continue in this thread

**Comment by ilyaszeke** [comment]
Thanks ❤️🙏🏻
