### ISSUE TITLE
[Question] PS4 SRD File UNPACK chunk images

### ISSUE THREAD

**Issue by l0ve2s** [redssu/Harmony-Tools#2]
PS4 SRD.file UNPACK chunk images
please confirm
Thank you.

PC SRD UNPACK
![kanban_JP](https://user-images.githubusercontent.com/88938174/202210787-d8e517a9-a3ea-41f9-b45b-545b5d20cdb4.png)

PS4 SRD UNPACK
![kanban_US](https://user-images.githubusercontent.com/88938174/202210697-f344c67f-fd74-4460-88e7-f6400721f0ce.png)

Raw texture 
![7](https://user-images.githubusercontent.com/88938174/202205323-031078ed-90d5-43b2-86ad-550c6a2f5908.png)
[PC startup_JP.zip](https://github.com/redssu/Harmony-Tools/files/10022735/PC.startup_JP.zip)
[PS4 startup_US.zip](https://github.com/redssu/Harmony-Tools/files/10022760/PS4.startup_US.zip)

**Comment by redssu** [comment]
Hi, 

as I wrote in [README.md](https://github.com/redssu/Harmony-Tools/blob/main/README.md) - my tools are mostly an overlay for V3Lib that's included in [DRV3-Sharp](https://github.com/CaptainSwag101/DRV3-Sharp) tools made by [CaptainSwag101](https://github.com/CaptainSwag101). At the moment, PS4 and PS Vita are not supported by his tools (as he wrote in the README) - and therefore neither are mine. 

Sorry.
