### ISSUE TITLE
the tool is not installed 

### ISSUE THREAD

**Issue by NeMilky** [redssu/Harmony-Tools#4]
I have done all the machinations that were in the installation instructions, but I either get an error or write that everything is installed, but the tool icons do not appear.

**Comment by redssu** [comment]
Hey,

could you please provide more details about the error you are encountering? Also, are you using a command-line interface with administrator privileges? This might be necessary to properly install the tools.

**Comment by NeMilky** [comment]
![Снимок экрана 2023-03-20 121349](https://user-images.githubusercontent.com/128281268/226295483-ba8cdc93-e24f-4501-b047-43910541707f.png)
Hello, yes, I run as admin. If I try to do the same with older versions of the tool, there is no error and writes that everything was successful, but the tool icons still do not appear(((
 Microsoft Windows [Version 10.0.22621.1413]
(c) Microsoft Corporation. All rights reserved.

C:{Windows\System32>cd %userprofile%\Documents\Harmony-Tools

C:\Users\Mika\Documents\Harmony-Tools>Harmony-Tools.exe context-menu register
"Harmony-Tools.exe" is not an internal or external
command, executable program or batch file.

**Comment by redssu** [comment]
Hey,

I apologize for the delay in getting back to you regarding your issue. 

It appears that there was an error in the documentation, the executable file name is in fact "HarmonyTools.exe" and not "Harmony-Tools.exe" as stated in documentation. I already corrected the docs. 

The correct command that you should execute is

```bash
HarmonyTools.exe context-menu register
```

Please let me know if you have any further questions or issues.

**Comment by NeMilky** [comment]
Hi, I recently moving from Windows 11 back to Windows 10 and your tool worked and everything works fine!!! Thank you so much for your wonderful tool and support!
